language: php

php:
  - 7.2

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-10-postgis-2.5

services:
  - mysql
  - postgresql

notifications:
  email: false

before_install:
  - mysql -e 'CREATE DATABASE laravel_geo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - psql -c 'CREATE DATABASE laravel_geo;' -U postgres

install:
  - echo 'DB_PASSWORD=' > tests/app/.env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - phpunit -v
