version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.3.9-buster
      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel_geo
      - image: circleci/mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel_geo
          MYSQL_USER: karomap
          MYSQL_PASSWORD: secret

    working_directory: ~/project

    steps:
      - checkout
      - run:
          name: Install required APT packages
          command: |
            sudo apt update
            sudo apt install -y libpq-dev
      - run:
          name: Install required PHP extensions
          command: sudo docker-php-ext-install bcmath pdo_mysql pdo_pgsql
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Install PHP dependencies
          command: |
            sudo composer self-update
            composer install --no-interaction --prefer-dist --no-suggest
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Create application environment
          command: |
            printf 'PGSQL_USERNAME=postgres\nPGSQL_PASSWORD=secret\nMYSQL_USERNAME=karomap\nMYSQL_PASSWORD=secret\n' > tests/app/.env
      - run:
          name: Run unit tests
          command: ./vendor/bin/phpunit -v
